# --- 
# Setup tergars for dev and prod code

function(setup_flags)

	set(CMAKE_CONFIGURATION_TYPES 
		DevDebug 
		DevRelease 
		DevRelWithDebInfo 
		DevMinSizeRel 

		ProdDebug 
		ProdRelease 
		ProdRelWithDebInfo 
		ProdMinSizeRel 
	CACHE TYPE INTERNAL FORCE)

	if (MSVC12 OR MSVC14)
		set(LIVERELEASE_CXX_FLAGS "/DLIVE_RELEASE /DSYNC_PLAYER")
		set(LIVERELEASE_C_FLAGS "${LIVERELEASE_CXX_FLAGS}")
		
		set(DEVMODE_CXX_FLAGS "/DDEVELOPMENT_MODE")
		set(DEVMODE_C_FLAGS "${LIVERELEASE_CXX_FLAGS}")
	endif()

	set(CMAKE_CXX_FLAGS_DEVDEBUG "${CMAKE_CXX_FLAGS_DEBUG} ${DEVMODE_CXX_FLAGS}" CACHE TYPE INTERNAL FORCE)
	set(CMAKE_CXX_FLAGS_DEVRELEASE "${CMAKE_CXX_FLAGS_RELEASE} ${DEVMODE_CXX_FLAGS}" CACHE TYPE INTERNAL FORCE)
	set(CMAKE_CXX_FLAGS_DEVRELWITHDEBINFO "${CMAKE_CXX_FLAGS_RELWITHDEBINFO} ${DEVMODE_CXX_FLAGS}" CACHE TYPE INTERNAL FORCE)
	set(CMAKE_CXX_FLAGS_DEVMINSIZEREL "${CMAKE_CXX_FLAGS_MINSIZEREL} ${DEVMODE_CXX_FLAGS}" CACHE TYPE INTERNAL FORCE)

	set(CMAKE_C_FLAGS_DEVDEBUG "${CMAKE_C_FLAGS_DEBUG} ${DEVMODE_C_FLAGS}" CACHE TYPE INTERNAL FORCE)
	set(CMAKE_C_FLAGS_DEVRELEASE "${CMAKE_C_FLAGS_RELEASE} ${DEVMODE_C_FLAGS}" CACHE TYPE INTERNAL FORCE)
	set(CMAKE_C_FLAGS_DEVRELWITHDEBINFO "${CMAKE_C_FLAGS_RELWITHDEBINFO} ${DEVMODE_C_FLAGS}" CACHE TYPE INTERNAL FORCE)
	set(CMAKE_C_FLAGS_DEVMINSIZEREL "${CMAKE_C_FLAGS_MINSIZEREL} ${DEVMODE_C_FLAGS}" CACHE TYPE INTERNAL FORCE)

	set(CMAKE_EXE_LINKER_FLAGS_DEVDEBUG "${CMAKE_EXE_LINKER_FLAGS_DEBUG}" CACHE TYPE INTERNAL FORCE)
	set(CMAKE_EXE_LINKER_FLAGS_DEVRELEASE "${CMAKE_EXE_LINKER_FLAGS_RELEASE}" CACHE TYPE INTERNAL FORCE)
	set(CMAKE_EXE_LINKER_FLAGS_DEVRELWITHDEBINFO "${CMAKE_EXE_LINKER_FLAGS_RELWITHDEBINFO}" CACHE TYPE INTERNAL FORCE)
	set(CMAKE_EXE_LINKER_FLAGS_DEVMINSIZEREL "${CMAKE_EXE_LINKER_FLAGS_MINSIZEREL}" CACHE TYPE INTERNAL FORCE)

	set(CMAKE_CXX_FLAGS_PRODDEBUG "${CMAKE_CXX_FLAGS_DEBUG} ${LIVERELEASE_CXX_FLAGS}" CACHE TYPE INTERNAL FORCE)
	set(CMAKE_CXX_FLAGS_PRODRELEASE "${CMAKE_CXX_FLAGS_RELEASE} ${LIVERELEASE_CXX_FLAGS}" CACHE TYPE INTERNAL FORCE)
	set(CMAKE_CXX_FLAGS_PRODRELWITHDEBINFO "${CMAKE_CXX_FLAGS_RELWITHDEBINFO} ${LIVERELEASE_CXX_FLAGS}" CACHE TYPE INTERNAL FORCE)
	set(CMAKE_CXX_FLAGS_PRODMINSIZEREL "${CMAKE_CXX_FLAGS_MINSIZEREL} ${LIVERELEASE_CXX_FLAGS}" CACHE TYPE INTERNAL FORCE)

	set(CMAKE_C_FLAGS_PRODDEBUG "${CMAKE_C_FLAGS_DEBUG} ${LIVERELEASE_C_FLAGS}" CACHE TYPE INTERNAL FORCE)
	set(CMAKE_C_FLAGS_PRODRELEASE "${CMAKE_C_FLAGS_RELEASE} ${LIVERELEASE_C_FLAGS}" CACHE TYPE INTERNAL FORCE)
	set(CMAKE_C_FLAGS_PRODRELWITHDEBINFO "${CMAKE_C_FLAGS_RELWITHDEBINFO} ${LIVERELEASE_C_FLAGS}" CACHE TYPE INTERNAL FORCE)
	set(CMAKE_C_FLAGS_PRODMINSIZEREL "${CMAKE_C_FLAGS_MINSIZEREL} ${LIVERELEASE_C_FLAGS}" CACHE TYPE INTERNAL FORCE)

	set(CMAKE_EXE_LINKER_FLAGS_PRODDEBUG "${CMAKE_EXE_LINKER_FLAGS_DEBUG}" CACHE TYPE INTERNAL FORCE)
	set(CMAKE_EXE_LINKER_FLAGS_PRODRELEASE "${CMAKE_EXE_LINKER_FLAGS_RELEASE}" CACHE TYPE INTERNAL FORCE)
	set(CMAKE_EXE_LINKER_FLAGS_PRODRELWITHDEBINFO "${CMAKE_EXE_LINKER_FLAGS_RELWITHDEBINFO}" CACHE TYPE INTERNAL FORCE)
	set(CMAKE_EXE_LINKER_FLAGS_PRODMINSIZEREL "${CMAKE_EXE_LINKER_FLAGS_MINSIZEREL}" CACHE TYPE INTERNAL FORCE)
	
	set(DEBUG_CONFIGURATIONS "DevDebug DevRelWithDebInfo ProdDebug ProdRelWithDebInfo" CACHE TYPE INTERNAL FORCE)

# ---
endfunction(setup_flags)